//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0010_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("mailAddressType", Namespace="http://www.ech.ch/xmlns/eCH-0010/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("mailAddress", Namespace="http://www.ech.ch/xmlns/eCH-0010/6")]
    public partial class MailAddressType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("organisation", Order=0)]
        public OrganisationMailAddressInfoType Organisation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("person", Order=1)]
        public PersonMailAddressInfoType Person { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("addressInformation", Order=2)]
        public AddressInformationType AddressInformation { get; set; }
    }
}
