//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0006_3_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("inhabitantControlType", Namespace="http://www.ech.ch/xmlns/eCH-0006/3")]
    public enum InhabitantControlType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0102")]
        Item0102,
        
        [System.Xml.Serialization.XmlEnumAttribute("0201")]
        Item0201,
        
        [System.Xml.Serialization.XmlEnumAttribute("0202")]
        Item0202,
        
        [System.Xml.Serialization.XmlEnumAttribute("0301")]
        Item0301,
        
        [System.Xml.Serialization.XmlEnumAttribute("0302")]
        Item0302,
        
        [System.Xml.Serialization.XmlEnumAttribute("0401")]
        Item0401,
        
        [System.Xml.Serialization.XmlEnumAttribute("0402")]
        Item0402,
        
        [System.Xml.Serialization.XmlEnumAttribute("0503")]
        Item0503,
        
        [System.Xml.Serialization.XmlEnumAttribute("0601")]
        Item0601,
        
        [System.Xml.Serialization.XmlEnumAttribute("0602")]
        Item0602,
        
        [System.Xml.Serialization.XmlEnumAttribute("0701")]
        Item0701,
        
        [System.Xml.Serialization.XmlEnumAttribute("0702")]
        Item0702,
        
        [System.Xml.Serialization.XmlEnumAttribute("0804")]
        Item0804,
        
        [System.Xml.Serialization.XmlEnumAttribute("0905")]
        Item0905,
        
        [System.Xml.Serialization.XmlEnumAttribute("1006")]
        Item1006,
        
        [System.Xml.Serialization.XmlEnumAttribute("1107")]
        Item1107,
        
        [System.Xml.Serialization.XmlEnumAttribute("1208")]
        Item1208,
        
        [System.Xml.Serialization.XmlEnumAttribute("1300")]
        Item1300,
    }
}
