//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0006_2_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residencePermitDetailedType", Namespace="http://www.ech.ch/xmlns/eCH-0006/2")]
    public enum ResidencePermitDetailedType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0102")]
        Item0102,
        
        [System.Xml.Serialization.XmlEnumAttribute("0201")]
        Item0201,
        
        [System.Xml.Serialization.XmlEnumAttribute("0202")]
        Item0202,
        
        [System.Xml.Serialization.XmlEnumAttribute("0301")]
        Item0301,
        
        [System.Xml.Serialization.XmlEnumAttribute("0302")]
        Item0302,
        
        [System.Xml.Serialization.XmlEnumAttribute("0401")]
        Item0401,
        
        [System.Xml.Serialization.XmlEnumAttribute("0402")]
        Item0402,
        
        [System.Xml.Serialization.XmlEnumAttribute("0503")]
        Item0503,
        
        [System.Xml.Serialization.XmlEnumAttribute("0601")]
        Item0601,
        
        [System.Xml.Serialization.XmlEnumAttribute("0602")]
        Item0602,
        
        [System.Xml.Serialization.XmlEnumAttribute("060101")]
        Item060101,
        
        [System.Xml.Serialization.XmlEnumAttribute("060201")]
        Item060201,
        
        [System.Xml.Serialization.XmlEnumAttribute("060102")]
        Item060102,
        
        [System.Xml.Serialization.XmlEnumAttribute("060202")]
        Item060202,
        
        [System.Xml.Serialization.XmlEnumAttribute("0701")]
        Item0701,
        
        [System.Xml.Serialization.XmlEnumAttribute("0702")]
        Item0702,
        
        [System.Xml.Serialization.XmlEnumAttribute("070101")]
        Item070101,
        
        [System.Xml.Serialization.XmlEnumAttribute("070201")]
        Item070201,
        
        [System.Xml.Serialization.XmlEnumAttribute("070102")]
        Item070102,
        
        [System.Xml.Serialization.XmlEnumAttribute("070202")]
        Item070202,
        
        [System.Xml.Serialization.XmlEnumAttribute("070103")]
        Item070103,
        
        [System.Xml.Serialization.XmlEnumAttribute("070104")]
        Item070104,
        
        [System.Xml.Serialization.XmlEnumAttribute("070204")]
        Item070204,
        
        [System.Xml.Serialization.XmlEnumAttribute("070105")]
        Item070105,
        
        [System.Xml.Serialization.XmlEnumAttribute("070205")]
        Item070205,
        
        [System.Xml.Serialization.XmlEnumAttribute("070206")]
        Item070206,
        
        [System.Xml.Serialization.XmlEnumAttribute("070907")]
        Item070907,
        
        [System.Xml.Serialization.XmlEnumAttribute("0804")]
        Item0804,
        
        [System.Xml.Serialization.XmlEnumAttribute("0905")]
        Item0905,
        
        [System.Xml.Serialization.XmlEnumAttribute("1006")]
        Item1006,
        
        [System.Xml.Serialization.XmlEnumAttribute("100601")]
        Item100601,
        
        [System.Xml.Serialization.XmlEnumAttribute("100602")]
        Item100602,
        
        [System.Xml.Serialization.XmlEnumAttribute("100603")]
        Item100603,
        
        [System.Xml.Serialization.XmlEnumAttribute("1107")]
        Item1107,
        
        [System.Xml.Serialization.XmlEnumAttribute("1208")]
        Item1208,
        
        [System.Xml.Serialization.XmlEnumAttribute("1300")]
        Item1300,
    }
}
