//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0011_9_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MaritalDataRestrictedPartnershipTypeMaritalStatus", Namespace="http://www.ech.ch/xmlns/eCH-0011/9", AnonymousType=true)]
    public enum MaritalDataRestrictedPartnershipTypeMaritalStatus
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
}
