//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0011_9_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("maritalDataRestrictedMaritalStatusPartnerType", Namespace="http://www.ech.ch/xmlns/eCH-0011/9")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaritalDataRestrictedMaritalStatusPartnerType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("maritalStatus", Order=0)]
        public MaritalDataRestrictedMaritalStatusPartnerTypeMaritalStatus MaritalStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dateOfMaritalStatus", Order=1, DataType="date")]
        public System.DateTime DateOfMaritalStatus { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("cancelationReason", Order=2)]
        public PartnershipAbolitionType CancelationReasonValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CancelationReason property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CancelationReasonValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<PartnershipAbolitionType> CancelationReason
        {
            get
            {
                if (this.CancelationReasonValueSpecified)
                {
                    return this.CancelationReasonValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CancelationReasonValue = value.GetValueOrDefault();
                this.CancelationReasonValueSpecified = value.HasValue;
            }
        }
    }
}
