//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0011_9_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("placeOfOriginType", Namespace="http://www.ech.ch/xmlns/eCH-0011/9")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("placeOfOriginType", Namespace="http://www.ech.ch/xmlns/eCH-0011/9")]
    public partial class PlaceOfOriginType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 300.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(300)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("originName", Order=0)]
        public string OriginName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("canton", Order=1)]
        public Ech0007_6_0.CantonAbbreviationType Canton { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("placeOfOriginId", Order=2)]
        public string PlaceOfOriginId { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 10001.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(int), "10001", "99999")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("historyMunicipalityId", Order=3)]
        public int HistoryMunicipalityIdValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the HistoryMunicipalityId property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool HistoryMunicipalityIdValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 10001.</para>
        /// <para xml:lang="en">Maximum inclusive value: 99999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> HistoryMunicipalityId
        {
            get
            {
                if (this.HistoryMunicipalityIdValueSpecified)
                {
                    return this.HistoryMunicipalityIdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.HistoryMunicipalityIdValue = value.GetValueOrDefault();
                this.HistoryMunicipalityIdValueSpecified = value.HasValue;
            }
        }
    }
}
