//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0011_9_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residencePermitDataType", Namespace="http://www.ech.ch/xmlns/eCH-0011/9")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResidencePermitDataType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("residencePermit", Order=0, IsNullable=true)]
        public System.Nullable<Ech0006_3_0.ResidencePermitType> ResidencePermit { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("residencePermitValidFrom", Order=1, DataType="date")]
        public System.DateTime ResidencePermitValidFromValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ResidencePermitValidFrom property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ResidencePermitValidFromValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ResidencePermitValidFrom
        {
            get
            {
                if (this.ResidencePermitValidFromValueSpecified)
                {
                    return this.ResidencePermitValidFromValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ResidencePermitValidFromValue = value.GetValueOrDefault();
                this.ResidencePermitValidFromValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("residencePermitValidTill", Order=2, DataType="date")]
        public System.DateTime ResidencePermitValidTillValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ResidencePermitValidTill property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ResidencePermitValidTillValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ResidencePermitValidTill
        {
            get
            {
                if (this.ResidencePermitValidTillValueSpecified)
                {
                    return this.ResidencePermitValidTillValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ResidencePermitValidTillValue = value.GetValueOrDefault();
                this.ResidencePermitValidTillValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("entryDate", Order=3, DataType="date")]
        public System.DateTime EntryDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the EntryDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EntryDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> EntryDate
        {
            get
            {
                if (this.EntryDateValueSpecified)
                {
                    return this.EntryDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EntryDateValue = value.GetValueOrDefault();
                this.EntryDateValueSpecified = value.HasValue;
            }
        }
    }
}
