//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0011_9_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residenceRegisterDataType", Namespace="http://www.ech.ch/xmlns/eCH-0011/9")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResidenceRegisterDataType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("federalRegister", Order=0)]
        public FederalRegisterType FederalRegisterValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FederalRegister property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool FederalRegisterValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<FederalRegisterType> FederalRegister
        {
            get
            {
                if (this.FederalRegisterValueSpecified)
                {
                    return this.FederalRegisterValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.FederalRegisterValue = value.GetValueOrDefault();
                this.FederalRegisterValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("reportingMunicipality", Order=1)]
        public Ech0007_6_0.SwissMunicipalityType ReportingMunicipality { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("arrivalDate", Order=2, DataType="date")]
        public System.DateTime ArrivalDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("comesFrom", Order=3)]
        public ResidenceRegisterDataTypeComesFrom ComesFrom { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dwellingAddress", Order=4)]
        public DwellingAddressType DwellingAddress { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("departureDate", Order=5, DataType="date")]
        public System.DateTime DepartureDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DepartureDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DepartureDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> DepartureDate
        {
            get
            {
                if (this.DepartureDateValueSpecified)
                {
                    return this.DepartureDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DepartureDateValue = value.GetValueOrDefault();
                this.DepartureDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("goesTo", Order=6)]
        public DestinationType GoesTo { get; set; }
    }
}
