//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0228_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VoteTypeBallotVariantBallot", Namespace="http://www.ech.ch/xmlns/eCH-0228/1", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoteTypeBallotVariantBallot
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VoteTypeBallotVariantBallotQuestionInformation> _questionInformation;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("questionInformation", Order=0)]
        public System.Collections.Generic.List<VoteTypeBallotVariantBallotQuestionInformation> QuestionInformation
        {
            get
            {
                return _questionInformation;
            }
            set
            {
                _questionInformation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VoteTypeBallotVariantBallot" /> class.</para>
        /// </summary>
        public VoteTypeBallotVariantBallot()
        {
            this._questionInformation = new System.Collections.Generic.List<VoteTypeBallotVariantBallotQuestionInformation>();
            this._tieBreakInformation = new System.Collections.Generic.List<VoteTypeBallotVariantBallotTieBreakInformation>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VoteTypeBallotVariantBallotTieBreakInformation> _tieBreakInformation;
        
        [System.Xml.Serialization.XmlElementAttribute("tieBreakInformation", Order=1)]
        public System.Collections.Generic.List<VoteTypeBallotVariantBallotTieBreakInformation> TieBreakInformation
        {
            get
            {
                return _tieBreakInformation;
            }
            set
            {
                _tieBreakInformation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TieBreakInformation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TieBreakInformationSpecified
        {
            get
            {
                return (this.TieBreakInformation != null);
            }
        }
    }
}
