//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0228_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VoteTypeBallotStandardBallotQuestionInformation", Namespace="http://www.ech.ch/xmlns/eCH-0228/1", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoteTypeBallotStandardBallotQuestionInformation
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("questionIdentification", Order=0)]
        public string QuestionIdentification { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("ballotQuestionNumber", Order=1)]
        public string BallotQuestionNumber { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<AnswerOptionType> _answerOption;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("answerOption", Order=2)]
        public System.Collections.Generic.List<AnswerOptionType> AnswerOption
        {
            get
            {
                return _answerOption;
            }
            set
            {
                _answerOption = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VoteTypeBallotStandardBallotQuestionInformation" /> class.</para>
        /// </summary>
        public VoteTypeBallotStandardBallotQuestionInformation()
        {
            this._answerOption = new System.Collections.Generic.List<AnswerOptionType>();
            this._ballotQuestion = new System.Collections.Generic.List<Ech0155_4_0.BallotQuestionTypeBallotQuestionInfo>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Ech0155_4_0.BallotQuestionTypeBallotQuestionInfo> _ballotQuestion;
        
        [System.Xml.Serialization.XmlArrayAttribute("ballotQuestion", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ballotQuestionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/4")]
        public System.Collections.Generic.List<Ech0155_4_0.BallotQuestionTypeBallotQuestionInfo> BallotQuestion
        {
            get
            {
                return _ballotQuestion;
            }
            set
            {
                _ballotQuestion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the BallotQuestion collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BallotQuestionSpecified
        {
            get
            {
                return (this.BallotQuestion != null);
            }
        }
    }
}
