//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0228_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("votingCardDeliveryType", Namespace="http://www.ech.ch/xmlns/eCH-0228/1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VotingCardDeliveryType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("contestData", Order=0)]
        public ContestDataType ContestData { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VotingCardDataType> _votingCardData;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("votingCardData", Order=1)]
        public System.Collections.Generic.List<VotingCardDataType> VotingCardData
        {
            get
            {
                return _votingCardData;
            }
            set
            {
                _votingCardData = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VotingCardDeliveryType" /> class.</para>
        /// </summary>
        public VotingCardDeliveryType()
        {
            this._votingCardData = new System.Collections.Generic.List<VotingCardDataType>();
            this._logisticCode = new System.Collections.Generic.List<NamedCodeType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NamedCodeType> _logisticCode;
        
        [System.Xml.Serialization.XmlElementAttribute("logisticCode", Order=2)]
        public System.Collections.Generic.List<NamedCodeType> LogisticCode
        {
            get
            {
                return _logisticCode;
            }
            set
            {
                _logisticCode = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the LogisticCode collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LogisticCodeSpecified
        {
            get
            {
                return (this.LogisticCode != null);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Order=3)]
        public Ech0155_4_0.ExtensionType Extension { get; set; }
    }
}
