// (c) Copyright by Abraxas Informatik AG
// For license information see LICENSE file

using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace Voting.Lib.ApiClientBase.DotNet.Services;

/// <summary>
/// The basic implementation for providing an http client for an api service.
/// </summary>
public class ServiceClientBase : IServiceClientBase
{
    /// <inheritdoc/>
    public Func<HttpClient>? HttpClientGenerationHandler { get; set; }

    /// <inheritdoc/>
    public string? BaseUrl { get; set; }

    /// <summary>
    /// Creates a new http client.
    /// </summary>
    /// <returns>The http client generated by the handler <see cref="HttpClientGenerationHandler"/>.</returns>
    /// <exception cref="InvalidOperationException">If no http client generation handler is configured.</exception>
    protected Task<HttpClient> CreateHttpClientAsync()
    {
        if (HttpClientGenerationHandler != null)
        {
            return Task.FromResult(HttpClientGenerationHandler());
        }
        else
        {
            throw new InvalidOperationException("No http client generation handler is registered.");
        }
    }
}
