//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0110_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CountOfVotersInformationTypeSubtotalInfo", Namespace="http://www.ech.ch/xmlns/eCH-0110/4", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountOfVotersInformationTypeSubtotalInfo
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("countOfVoters", Order=0)]
        public string CountOfVoters { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("voterType", Order=1)]
        public Ech0155_4_0.VoterTypeType VoterTypeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VoterType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool VoterTypeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Ech0155_4_0.VoterTypeType> VoterType
        {
            get
            {
                if (this.VoterTypeValueSpecified)
                {
                    return this.VoterTypeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.VoterTypeValue = value.GetValueOrDefault();
                this.VoterTypeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("sex", Order=2)]
        public Ech0044_4_1.SexType SexValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Sex property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SexValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Ech0044_4_1.SexType> Sex
        {
            get
            {
                if (this.SexValueSpecified)
                {
                    return this.SexValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SexValue = value.GetValueOrDefault();
                this.SexValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("allowsEvoting", Order=3)]
        public bool AllowsEvotingValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AllowsEvoting property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AllowsEvotingValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> AllowsEvoting
        {
            get
            {
                if (this.AllowsEvotingValueSpecified)
                {
                    return this.AllowsEvotingValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AllowsEvotingValue = value.GetValueOrDefault();
                this.AllowsEvotingValueSpecified = value.HasValue;
            }
        }
    }
}
