//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0110_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("standardBallotResultType", Namespace="http://www.ech.ch/xmlns/eCH-0110/4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StandardBallotResultType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("questionIdentification", Order=0)]
        public string QuestionIdentification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("answerType", Order=1)]
        public Ech0155_4_0.AnswerInformationType AnswerType { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Ech0155_4_0.BallotQuestionTypeBallotQuestionInfo> _question;
        
        [System.Xml.Serialization.XmlArrayAttribute("question", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ballotQuestionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/4")]
        public System.Collections.Generic.List<Ech0155_4_0.BallotQuestionTypeBallotQuestionInfo> Question
        {
            get
            {
                return _question;
            }
            set
            {
                _question = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Question collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuestionSpecified
        {
            get
            {
                return (this.Question != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StandardBallotResultType" /> class.</para>
        /// </summary>
        public StandardBallotResultType()
        {
            this._question = new System.Collections.Generic.List<Ech0155_4_0.BallotQuestionTypeBallotQuestionInfo>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("countOfAnswerYes", Order=3)]
        public ResultDetailType CountOfAnswerYes { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("countOfAnswerNo", Order=4)]
        public ResultDetailType CountOfAnswerNo { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("countOfAnswerInvalid", Order=5)]
        public ResultDetailType CountOfAnswerInvalid { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("countOfAnswerEmpty", Order=6)]
        public ResultDetailType CountOfAnswerEmpty { get; set; }
    }
}
