//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0155_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("votingCardType", Namespace="http://www.ech.ch/xmlns/eCH-0155/4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("votingCard", Namespace="http://www.ech.ch/xmlns/eCH-0155/4")]
    public partial class VotingCardType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("votingCardNumber", Order=0)]
        public string VotingCardNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("votingPersonIdentification", Order=1)]
        public VotingPersonIdentificationType VotingPersonIdentification { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DomainOfInfluenceType> _domainOfInfluence;
        
        [System.Xml.Serialization.XmlElementAttribute("domainOfInfluence", Order=2)]
        public System.Collections.Generic.List<DomainOfInfluenceType> DomainOfInfluence
        {
            get
            {
                return _domainOfInfluence;
            }
            set
            {
                _domainOfInfluence = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DomainOfInfluence collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DomainOfInfluenceSpecified
        {
            get
            {
                return ((this.DomainOfInfluence != null) 
                            && (this.DomainOfInfluence.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VotingCardType" /> class.</para>
        /// </summary>
        public VotingCardType()
        {
            this._domainOfInfluence = new System.Collections.Generic.List<DomainOfInfluenceType>();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("voterType", Order=3)]
        public VoterTypeType VoterTypeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VoterType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool VoterTypeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<VoterTypeType> VoterType
        {
            get
            {
                if (this.VoterTypeValueSpecified)
                {
                    return this.VoterTypeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.VoterTypeValue = value.GetValueOrDefault();
                this.VoterTypeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("votingChannel", Order=4)]
        public VotingChannelType VotingChannelValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VotingChannel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool VotingChannelValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<VotingChannelType> VotingChannel
        {
            get
            {
                if (this.VotingChannelValueSpecified)
                {
                    return this.VotingChannelValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.VotingChannelValue = value.GetValueOrDefault();
                this.VotingChannelValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("dateOfVoting", Order=5, DataType="date")]
        public System.DateTime DateOfVotingValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DateOfVoting property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DateOfVotingValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> DateOfVoting
        {
            get
            {
                if (this.DateOfVotingValueSpecified)
                {
                    return this.DateOfVotingValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DateOfVotingValue = value.GetValueOrDefault();
                this.DateOfVotingValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("timeOfVoting", Order=6, DataType="time")]
        public System.DateTime TimeOfVotingValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TimeOfVoting property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TimeOfVotingValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> TimeOfVoting
        {
            get
            {
                if (this.TimeOfVotingValueSpecified)
                {
                    return this.TimeOfVotingValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TimeOfVotingValue = value.GetValueOrDefault();
                this.TimeOfVotingValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Xml.Serialization.XmlElementAttribute("placeOfVoting", Order=7)]
        public string PlaceOfVoting { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("electronicVotingCardYesNo", Order=8)]
        public bool ElectronicVotingCardYesNoValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ElectronicVotingCardYesNo property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ElectronicVotingCardYesNoValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> ElectronicVotingCardYesNo
        {
            get
            {
                if (this.ElectronicVotingCardYesNoValueSpecified)
                {
                    return this.ElectronicVotingCardYesNoValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ElectronicVotingCardYesNoValue = value.GetValueOrDefault();
                this.ElectronicVotingCardYesNoValueSpecified = value.HasValue;
            }
        }
    }
}
