//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0155_5_2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("electionType", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("election", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    public partial class ElectionType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("electionIdentification", Order=0)]
        public string ElectionIdentification { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<OtherIdentificationType> _otherIdentification;
        
        [System.Xml.Serialization.XmlElementAttribute("otherIdentification", Order=1)]
        public System.Collections.Generic.List<OtherIdentificationType> OtherIdentification
        {
            get
            {
                return _otherIdentification;
            }
            set
            {
                _otherIdentification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the OtherIdentification collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherIdentificationSpecified
        {
            get
            {
                return (this.OtherIdentification != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectionType" /> class.</para>
        /// </summary>
        public ElectionType()
        {
            this._otherIdentification = new System.Collections.Generic.List<OtherIdentificationType>();
            this._electionDescription = new System.Collections.Generic.List<ElectionDescriptionInformationTypeElectionDescriptionInfo>();
            this._referencedElection = new System.Collections.Generic.List<ReferencedElectionInformationType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("typeOfElection", Order=2)]
        public TypeOfElectionType TypeOfElection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("electionPosition", Order=3)]
        public string ElectionPosition { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectionDescriptionInformationTypeElectionDescriptionInfo> _electionDescription;
        
        [System.Xml.Serialization.XmlArrayAttribute("electionDescription", Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("electionDescriptionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
        public System.Collections.Generic.List<ElectionDescriptionInformationTypeElectionDescriptionInfo> ElectionDescription
        {
            get
            {
                return _electionDescription;
            }
            set
            {
                _electionDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ElectionDescription collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectionDescriptionSpecified
        {
            get
            {
                return (this.ElectionDescription != null);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("numberOfMandates", Order=5)]
        public string NumberOfMandates { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ReferencedElectionInformationType> _referencedElection;
        
        [System.Xml.Serialization.XmlElementAttribute("referencedElection", Order=6)]
        public System.Collections.Generic.List<ReferencedElectionInformationType> ReferencedElection
        {
            get
            {
                return _referencedElection;
            }
            set
            {
                _referencedElection = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ReferencedElection collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencedElectionSpecified
        {
            get
            {
                return (this.ReferencedElection != null);
            }
        }
    }
}
