//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0155_5_2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ElectronicBallotTypeStandardElectronicBallot", Namespace="http://www.ech.ch/xmlns/eCH-0155/5", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectronicBallotTypeStandardElectronicBallot
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("questionIdentification", Order=0)]
        public string QuestionIdentification { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("electronicBallotQuestionNumber", Order=1)]
        public string ElectronicBallotQuestionNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("answerInformation", Order=2)]
        public AnswerInformationType AnswerInformation { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectronicBallotQuestionTypeElectronicBallotQuestionInfo> _electronicBallotQuestion;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("electronicBallotQuestion", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("electronicBallotQuestionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
        public System.Collections.Generic.List<ElectronicBallotQuestionTypeElectronicBallotQuestionInfo> ElectronicBallotQuestion
        {
            get
            {
                return _electronicBallotQuestion;
            }
            set
            {
                _electronicBallotQuestion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectronicBallotTypeStandardElectronicBallot" /> class.</para>
        /// </summary>
        public ElectronicBallotTypeStandardElectronicBallot()
        {
            this._electronicBallotQuestion = new System.Collections.Generic.List<ElectronicBallotQuestionTypeElectronicBallotQuestionInfo>();
        }
    }
}
