//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0155_5_2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("listUnionType", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListUnionType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("listUnionIdentification", Order=0)]
        public string ListUnionIdentification { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ListUnionDescriptionTypeListUnionDescriptionInfo> _listUnionDescription;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("listUnionDescription", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("listUnionDescriptionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
        public System.Collections.Generic.List<ListUnionDescriptionTypeListUnionDescriptionInfo> ListUnionDescription
        {
            get
            {
                return _listUnionDescription;
            }
            set
            {
                _listUnionDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ListUnionType" /> class.</para>
        /// </summary>
        public ListUnionType()
        {
            this._listUnionDescription = new System.Collections.Generic.List<ListUnionDescriptionTypeListUnionDescriptionInfo>();
            this._referencedList = new System.Collections.Generic.List<string>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("listUnionType", Order=2)]
        public ListRelationType ListUnionTypeProperty { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<string> _referencedList;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("referencedList", Order=3)]
        public System.Collections.Generic.List<string> ReferencedList
        {
            get
            {
                return _referencedList;
            }
            set
            {
                _referencedList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("referencedListUnion", Order=4)]
        public string ReferencedListUnion { get; set; }
    }
}
