//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0228_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VotingCardIndividualCodesTypeElectionGroupBallot", Namespace="http://www.ech.ch/xmlns/eCH-0228/1", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VotingCardIndividualCodesTypeElectionGroupBallot
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("electionGroupIdentification", Order=0)]
        public string ElectionGroupIdentification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("electionGroupDescription", Order=1)]
        public Ech0155_4_0.ElectionGroupDescriptionType ElectionGroupDescription { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("electionGroupPosition", Order=2)]
        public string ElectionGroupPosition { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectionInformationType> _electionInformation;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("electionInformation", Order=3)]
        public System.Collections.Generic.List<ElectionInformationType> ElectionInformation
        {
            get
            {
                return _electionInformation;
            }
            set
            {
                _electionInformation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VotingCardIndividualCodesTypeElectionGroupBallot" /> class.</para>
        /// </summary>
        public VotingCardIndividualCodesTypeElectionGroupBallot()
        {
            this._electionInformation = new System.Collections.Generic.List<ElectionInformationType>();
            this._individualElectionGroupVerificationCodes = new System.Collections.Generic.List<NamedCodeType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NamedCodeType> _individualElectionGroupVerificationCodes;
        
        [System.Xml.Serialization.XmlElementAttribute("individualElectionGroupVerificationCodes", Order=4)]
        public System.Collections.Generic.List<NamedCodeType> IndividualElectionGroupVerificationCodes
        {
            get
            {
                return _individualElectionGroupVerificationCodes;
            }
            set
            {
                _individualElectionGroupVerificationCodes = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the IndividualElectionGroupVerificationCodes collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndividualElectionGroupVerificationCodesSpecified
        {
            get
            {
                return ((this.IndividualElectionGroupVerificationCodes != null) 
                            && (this.IndividualElectionGroupVerificationCodes.Count != 0));
            }
        }
    }
}
