//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0155_5_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("electronicBallotQuestionType", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectronicBallotQuestionType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectronicBallotQuestionTypeElectronicBallotQuestionInfo> _electronicBallotQuestionInfo;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("electronicBallotQuestionInfo", Order=0)]
        public System.Collections.Generic.List<ElectronicBallotQuestionTypeElectronicBallotQuestionInfo> ElectronicBallotQuestionInfo
        {
            get
            {
                return _electronicBallotQuestionInfo;
            }
            set
            {
                _electronicBallotQuestionInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectronicBallotQuestionType" /> class.</para>
        /// </summary>
        public ElectronicBallotQuestionType()
        {
            this._electronicBallotQuestionInfo = new System.Collections.Generic.List<ElectronicBallotQuestionTypeElectronicBallotQuestionInfo>();
        }
    }
}
