//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0011_8_1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("placeOfOriginType", Namespace="http://www.ech.ch/xmlns/eCH-0011/8")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("placeOfOriginType", Namespace="http://www.ech.ch/xmlns/eCH-0011/8")]
    public partial class PlaceOfOriginType
    {
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("originName", Order=0)]
        public string OriginName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("canton", Order=1)]
        public Ech0007_5_0.CantonAbbreviationType Canton { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("placeOfOriginId", Order=2)]
        public string PlaceOfOriginId { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("historyMunicipalityId", Order=3)]
        public int HistoryMunicipalityIdValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the HistoryMunicipalityId property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool HistoryMunicipalityIdValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> HistoryMunicipalityId
        {
            get
            {
                if (this.HistoryMunicipalityIdValueSpecified)
                {
                    return this.HistoryMunicipalityIdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.HistoryMunicipalityIdValue = value.GetValueOrDefault();
                this.HistoryMunicipalityIdValueSpecified = value.HasValue;
            }
        }
    }
}
