//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0011_8_1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residenceDataType", Namespace="http://www.ech.ch/xmlns/eCH-0011/8")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherResidenceTypeSecondaryResidence))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecondaryResidenceTypeSecondaryResidence))]
    public partial class ResidenceDataType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reportingMunicipality", Order=0)]
        public Ech0007_5_0.SwissMunicipalityType ReportingMunicipality { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("arrivalDate", Order=1, DataType="date")]
        public System.DateTime ArrivalDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("comesFrom", Order=2)]
        public DestinationType ComesFrom { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dwellingAddress", Order=3)]
        public DwellingAddressType DwellingAddress { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("departureDate", Order=4, DataType="date")]
        public System.DateTime DepartureDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DepartureDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DepartureDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> DepartureDate
        {
            get
            {
                if (this.DepartureDateValueSpecified)
                {
                    return this.DepartureDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DepartureDateValue = value.GetValueOrDefault();
                this.DepartureDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("goesTo", Order=5)]
        public DestinationType GoesTo { get; set; }
    }
}
