//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0098_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("destinationType", Namespace="http://www.ech.ch/xmlns/eCH-0098/4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("destinationType", Namespace="http://www.ech.ch/xmlns/eCH-0098/4")]
    public partial class DestinationType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("unknown", Order=0)]
        public UnknownType UnknownValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Unknown property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UnknownValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<UnknownType> Unknown
        {
            get
            {
                if (this.UnknownValueSpecified)
                {
                    return this.UnknownValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UnknownValue = value.GetValueOrDefault();
                this.UnknownValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("swissTown", Order=1)]
        public Ech0007_6_0.SwissMunicipalityType SwissTown { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("foreignCountry", Order=2)]
        public DestinationTypeForeignCountry ForeignCountry { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("mailAddress", Order=3)]
        public Ech0010_6_0.AddressInformationType MailAddress { get; set; }
    }
}
