//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0098_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SwissHeadquarterTypeBusinessAddress", Namespace="http://www.ech.ch/xmlns/eCH-0098/4", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwissHeadquarterTypeBusinessAddress
    {
        
        [System.Xml.Serialization.XmlElementAttribute("organisation", Order=0)]
        public Ech0010_6_0.OrganisationMailAddressInfoType Organisation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("person", Order=1)]
        public Ech0010_6_0.PersonMailAddressInfoType Person { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("addressInformation", Order=2)]
        public Ech0010_6_0.SwissAddressInformationType AddressInformation { get; set; }
    }
}
