//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0098_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("yesNoType", Namespace="http://www.ech.ch/xmlns/eCH-0098/4")]
    [System.Xml.Serialization.XmlRootAttribute("yesNoType", Namespace="http://www.ech.ch/xmlns/eCH-0098/4")]
    public enum YesNoType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
}
