//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0045_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("foreignerPersonType", Namespace="http://www.ech.ch/xmlns/eCH-0045/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignerPersonType : PersonType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("nameOnForeignPassport", Order=0)]
        public Ech0011_9_0.ForeignerNameType NameOnForeignPassport { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("declaredForeignName", Order=1)]
        public Ech0011_9_0.ForeignerNameType DeclaredForeignName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("residencePermit", Order=2)]
        public Ech0011_9_0.ResidencePermitDataType ResidencePermit { get; set; }
    }
}
