//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0045_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("swissPersonType", Namespace="http://www.ech.ch/xmlns/eCH-0045/6")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwissPersonType : PersonType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Ech0011_9_0.PlaceOfOriginType> _placeOfOrigin;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("placeOfOrigin", Order=0)]
        public System.Collections.Generic.List<Ech0011_9_0.PlaceOfOriginType> PlaceOfOrigin
        {
            get
            {
                return _placeOfOrigin;
            }
            set
            {
                _placeOfOrigin = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SwissPersonType" /> class.</para>
        /// </summary>
        public SwissPersonType()
        {
            this._placeOfOrigin = new System.Collections.Generic.List<Ech0011_9_0.PlaceOfOriginType>();
            this._placeOfOriginAddonData = new System.Collections.Generic.List<Ech0021_8_0.PlaceOfOriginAddonDataType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Ech0021_8_0.PlaceOfOriginAddonDataType> _placeOfOriginAddonData;
        
        [System.Xml.Serialization.XmlElementAttribute("placeOfOriginAddonData", Order=1)]
        public System.Collections.Generic.List<Ech0021_8_0.PlaceOfOriginAddonDataType> PlaceOfOriginAddonData
        {
            get
            {
                return _placeOfOriginAddonData;
            }
            set
            {
                _placeOfOriginAddonData = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PlaceOfOriginAddonData collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlaceOfOriginAddonDataSpecified
        {
            get
            {
                return (this.PlaceOfOriginAddonData != null);
            }
        }
    }
}
