//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace AbxVoting_1_5
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("delivery", Namespace="http://www.abraxas.ch/xmlns/ABX-Voting/1", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("delivery", Namespace="http://www.abraxas.ch/xmlns/ABX-Voting/1")]
    public partial class Delivery
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("deliveryHeader", Order=0)]
        public Ech0058_5_0.HeaderType DeliveryHeader { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("baseDelivery", Order=1)]
        public EventBaseDelivery BaseDelivery { get; set; }
    }
}
