//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace ABX_Voting_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("eventBaseDelivery", Namespace="http://www.abraxas.ch/xmlns/ABX-Voting/1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EventBaseDelivery
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<PersonInfoType> _person;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("person", Order=0)]
        public System.Collections.Generic.List<PersonInfoType> Person
        {
            get
            {
                return _person;
            }
            set
            {
                _person = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EventBaseDelivery" /> class.</para>
        /// </summary>
        public EventBaseDelivery()
        {
            this._person = new System.Collections.Generic.List<PersonInfoType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Order=1)]
        public object Extension { get; set; }
    }
}
