//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0252_2_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DrawElectionTypeProportionalElection", Namespace="http://www.ech.ch/xmlns/eCH-0252/2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DrawElectionTypeProportionalElection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DrawElectionTypeProportionalElectionListOrListUnionDrawElection> _listOrListUnionDrawElection;
        
        [System.Xml.Serialization.XmlElementAttribute("listOrListUnionDrawElection", Order=0)]
        public System.Collections.Generic.List<DrawElectionTypeProportionalElectionListOrListUnionDrawElection> ListOrListUnionDrawElection
        {
            get
            {
                return _listOrListUnionDrawElection;
            }
            set
            {
                _listOrListUnionDrawElection = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListOrListUnionDrawElection collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListOrListUnionDrawElectionSpecified
        {
            get
            {
                return ((this.ListOrListUnionDrawElection != null) 
                            && (this.ListOrListUnionDrawElection.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="DrawElectionTypeProportionalElection" /> class.</para>
        /// </summary>
        public DrawElectionTypeProportionalElection()
        {
            this._listOrListUnionDrawElection = new System.Collections.Generic.List<DrawElectionTypeProportionalElectionListOrListUnionDrawElection>();
            this._candidateDrawElectionOnList = new System.Collections.Generic.List<DrawElectionTypeProportionalElectionCandidateDrawElectionOnList>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<DrawElectionTypeProportionalElectionCandidateDrawElectionOnList> _candidateDrawElectionOnList;
        
        [System.Xml.Serialization.XmlElementAttribute("candidateDrawElectionOnList", Order=1)]
        public System.Collections.Generic.List<DrawElectionTypeProportionalElectionCandidateDrawElectionOnList> CandidateDrawElectionOnList
        {
            get
            {
                return _candidateDrawElectionOnList;
            }
            set
            {
                _candidateDrawElectionOnList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CandidateDrawElectionOnList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CandidateDrawElectionOnListSpecified
        {
            get
            {
                return ((this.CandidateDrawElectionOnList != null) 
                            && (this.CandidateDrawElectionOnList.Count != 0));
            }
        }
    }
}
