//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0252_2_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("electedType", Namespace="http://www.ech.ch/xmlns/eCH-0252/2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectedType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("majorityElection", Order=0)]
        public ElectedTypeMajorityElection MajorityElection { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("proportionalElection", Order=1)]
        public ElectedTypeProportionalElection ProportionalElection { get; set; }
    }
}
