//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0252_2_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EventElectionResultDeliveryTypeElectionGroupResultElectionResult", Namespace="http://www.ech.ch/xmlns/eCH-0252/2", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EventElectionResultDeliveryTypeElectionGroupResultElectionResult
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("electionIdentification", Order=0)]
        public string ElectionIdentification { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NamedIdType> _otherIdentification;
        
        [System.Xml.Serialization.XmlElementAttribute("otherIdentification", Order=1)]
        public System.Collections.Generic.List<NamedIdType> OtherIdentification
        {
            get
            {
                return _otherIdentification;
            }
            set
            {
                _otherIdentification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the OtherIdentification collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OtherIdentificationSpecified
        {
            get
            {
                return (this.OtherIdentification != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EventElectionResultDeliveryTypeElectionGroupResultElectionResult" /> class.</para>
        /// </summary>
        public EventElectionResultDeliveryTypeElectionGroupResultElectionResult()
        {
            this._otherIdentification = new System.Collections.Generic.List<NamedIdType>();
            this._candidate = new System.Collections.Generic.List<CandidateType>();
            this._countingCircleResult = new System.Collections.Generic.List<CountingCircleResultType>();
            this._namedElement = new System.Collections.Generic.List<NamedElementType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CandidateType> _candidate;
        
        [System.Xml.Serialization.XmlElementAttribute("candidate", Order=2)]
        public System.Collections.Generic.List<CandidateType> Candidate
        {
            get
            {
                return _candidate;
            }
            set
            {
                _candidate = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Candidate collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CandidateSpecified
        {
            get
            {
                return (this.Candidate != null);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<CountingCircleResultType> _countingCircleResult;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("countingCircleResult", Order=3)]
        public System.Collections.Generic.List<CountingCircleResultType> CountingCircleResult
        {
            get
            {
                return _countingCircleResult;
            }
            set
            {
                _countingCircleResult = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("elected", Order=4)]
        public ElectedType Elected { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("drawElection", Order=5)]
        public DrawElectionType DrawElection { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NamedElementType> _namedElement;
        
        [System.Xml.Serialization.XmlElementAttribute("namedElement", Order=6)]
        public System.Collections.Generic.List<NamedElementType> NamedElement
        {
            get
            {
                return _namedElement;
            }
            set
            {
                _namedElement = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NamedElement collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NamedElementSpecified
        {
            get
            {
                return (this.NamedElement != null);
            }
        }
    }
}
