//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0252_2_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MandateTypeTypeMandateTypeOther", Namespace="http://www.ech.ch/xmlns/eCH-0252/2", AnonymousType=true)]
    public enum MandateTypeTypeMandateTypeOther
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
}
