//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0007_6_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("municipalityRoot", Namespace="http://www.ech.ch/xmlns/eCH-0007/6", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("municipalityRoot", Namespace="http://www.ech.ch/xmlns/eCH-0007/6")]
    public partial class MunicipalityRoot
    {
        
        [System.Xml.Serialization.XmlElementAttribute("swissMunicipality", Order=0)]
        public SwissMunicipalityType SwissMunicipality { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("swissAndFlMunicipality", Order=1)]
        public SwissAndFlMunicipalityType SwissAndFlMunicipality { get; set; }
    }
}
