//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0222_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ElectionRawDataTypeBallotRawDataBallotPosition", Namespace="http://www.ech.ch/xmlns/eCH-0222/1", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectionRawDataTypeBallotRawDataBallotPosition
    {
        
        [System.Xml.Serialization.XmlElementAttribute("candidate", Order=0)]
        public ElectionRawDataTypeBallotRawDataBallotPositionCandidate Candidate { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _isEmpty = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute("isEmpty", Order=1)]
        public bool IsEmpty
        {
            get
            {
                return _isEmpty;
            }
            set
            {
                _isEmpty = value;
            }
        }
    }
}
