//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0222_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ElectionRawDataTypeBallotRawData", Namespace="http://www.ech.ch/xmlns/eCH-0222/1", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectionRawDataTypeBallotRawData
    {
        
        /// <summary>
        /// <para>mandatory for proportional elections</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("mandatory for proportional elections")]
        [System.Xml.Serialization.XmlElementAttribute("listRawData", Order=0)]
        public ElectionRawDataTypeBallotRawDataListRawData ListRawData { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectionRawDataTypeBallotRawDataBallotPosition> _ballotPosition;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ballotPosition", Order=1)]
        public System.Collections.Generic.List<ElectionRawDataTypeBallotRawDataBallotPosition> BallotPosition
        {
            get
            {
                return _ballotPosition;
            }
            set
            {
                _ballotPosition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectionRawDataTypeBallotRawData" /> class.</para>
        /// </summary>
        public ElectionRawDataTypeBallotRawData()
        {
            this._ballotPosition = new System.Collections.Generic.List<ElectionRawDataTypeBallotRawDataBallotPosition>();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("isUnchangedBallot", Order=2)]
        public bool IsUnchangedBallotValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsUnchangedBallot property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsUnchangedBallotValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsUnchangedBallot
        {
            get
            {
                if (this.IsUnchangedBallotValueSpecified)
                {
                    return this.IsUnchangedBallotValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsUnchangedBallotValue = value.GetValueOrDefault();
                this.IsUnchangedBallotValueSpecified = value.HasValue;
            }
        }
    }
}
