//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0021_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("guardianMeasureInfoType", Namespace="http://www.ech.ch/xmlns/eCH-0021/7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardianMeasureInfoType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<BasedOnLawType> _basedOnLaw;
        
        [System.Xml.Serialization.XmlElementAttribute("basedOnLaw", Order=0)]
        public System.Collections.Generic.List<BasedOnLawType> BasedOnLaw
        {
            get
            {
                return _basedOnLaw;
            }
            set
            {
                _basedOnLaw = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the BasedOnLaw collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BasedOnLawSpecified
        {
            get
            {
                return ((this.BasedOnLaw != null) 
                            && (this.BasedOnLaw.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GuardianMeasureInfoType" /> class.</para>
        /// </summary>
        public GuardianMeasureInfoType()
        {
            this._basedOnLaw = new System.Collections.Generic.List<BasedOnLawType>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Xml.Serialization.XmlElementAttribute("basedOnLawAddOn", Order=1)]
        public string BasedOnLawAddOn { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("guardianMeasureValidFrom", Order=2, DataType="date")]
        public System.DateTime GuardianMeasureValidFrom { get; set; }
    }
}
