//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0021_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("personAddonType", Namespace="http://www.ech.ch/xmlns/eCH-0021/7")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonAddonType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("personidentification", Order=0)]
        public Ech0044_4_1.PersonIdentificationType Personidentification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("personAdditionalData", Order=1)]
        public PersonAdditionalData PersonAdditionalData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("politicalRightData", Order=2)]
        public PoliticalRightDataType PoliticalRightData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("birthAddonData", Order=3)]
        public BirthAddonDataType BirthAddonData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lockData", Order=4)]
        public LockDataType LockData { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<PlaceOfOriginAddonDataType> _placeOfOriginAddonData;
        
        [System.Xml.Serialization.XmlElementAttribute("placeOfOriginAddonData", Order=5)]
        public System.Collections.Generic.List<PlaceOfOriginAddonDataType> PlaceOfOriginAddonData
        {
            get
            {
                return _placeOfOriginAddonData;
            }
            set
            {
                _placeOfOriginAddonData = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PlaceOfOriginAddonData collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PlaceOfOriginAddonDataSpecified
        {
            get
            {
                return (this.PlaceOfOriginAddonData != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PersonAddonType" /> class.</para>
        /// </summary>
        public PersonAddonType()
        {
            this._placeOfOriginAddonData = new System.Collections.Generic.List<PlaceOfOriginAddonDataType>();
            this._parentalRelationship = new System.Collections.Generic.List<ParentalRelationshipType>();
            this._guardianRelationship = new System.Collections.Generic.List<GuardianRelationshipType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("jobData", Order=6)]
        public JobDataType JobData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maritalRelationship", Order=7)]
        public MaritalRelationshipType MaritalRelationship { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ParentalRelationshipType> _parentalRelationship;
        
        [System.Xml.Serialization.XmlElementAttribute("parentalRelationship", Order=8)]
        public System.Collections.Generic.List<ParentalRelationshipType> ParentalRelationship
        {
            get
            {
                return _parentalRelationship;
            }
            set
            {
                _parentalRelationship = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ParentalRelationship collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParentalRelationshipSpecified
        {
            get
            {
                return (this.ParentalRelationship != null);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<GuardianRelationshipType> _guardianRelationship;
        
        [System.Xml.Serialization.XmlElementAttribute("guardianRelationship", Order=9)]
        public System.Collections.Generic.List<GuardianRelationshipType> GuardianRelationship
        {
            get
            {
                return _guardianRelationship;
            }
            set
            {
                _guardianRelationship = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the GuardianRelationship collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GuardianRelationshipSpecified
        {
            get
            {
                return (this.GuardianRelationship != null);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("armedForcesData", Order=10)]
        public ArmedForcesDataType ArmedForcesData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("civilDefenseData", Order=11)]
        public CivilDefenseDataType CivilDefenseData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fireServiceData", Order=12)]
        public FireServiceDataType FireServiceData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("healthInsuranceData", Order=13)]
        public HealthInsuranceDataType HealthInsuranceData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("matrimonialInheritanceArrangementData", Order=14)]
        public MatrimonialInheritanceArrangementDataType MatrimonialInheritanceArrangementData { get; set; }
    }
}
