//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0222_3_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("VoteRawDataTypeBallotRawDataBallotCastedQuestionRawDataCasted", Namespace="http://www.ech.ch/xmlns/eCH-0222/3", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VoteRawDataTypeBallotRawDataBallotCastedQuestionRawDataCasted
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("castedVote", Order=0)]
        public string CastedVote { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("answerOptionIdentification", Order=1)]
        public Ech0155_5_1.AnswerOptionIdentificationType AnswerOptionIdentification { get; set; }
    }
}
