//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0222_3_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("votingCardsResultDetailType", Namespace="http://www.ech.ch/xmlns/eCH-0222/3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VotingCardsResultDetailType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("countOfReceivedVotingCards", Order=0)]
        public string CountOfReceivedVotingCards { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("voterType", Order=1)]
        public Ech0155_5_1.VoterTypeType VoterTypeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the VoterType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool VoterTypeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Ech0155_5_1.VoterTypeType> VoterType
        {
            get
            {
                if (this.VoterTypeValueSpecified)
                {
                    return this.VoterTypeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.VoterTypeValue = value.GetValueOrDefault();
                this.VoterTypeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("allowsEvoting", Order=2)]
        public bool AllowsEvotingValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AllowsEvoting property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AllowsEvotingValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> AllowsEvoting
        {
            get
            {
                if (this.AllowsEvotingValueSpecified)
                {
                    return this.AllowsEvotingValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AllowsEvotingValue = value.GetValueOrDefault();
                this.AllowsEvotingValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("valid", Order=3)]
        public bool ValidValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Valid property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ValidValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Valid
        {
            get
            {
                if (this.ValidValueSpecified)
                {
                    return this.ValidValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ValidValue = value.GetValueOrDefault();
                this.ValidValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("channel", Order=4)]
        public Ech0155_5_1.VotingChannelType ChannelValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Channel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ChannelValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Ech0155_5_1.VotingChannelType> Channel
        {
            get
            {
                if (this.ChannelValueSpecified)
                {
                    return this.ChannelValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ChannelValue = value.GetValueOrDefault();
                this.ChannelValueSpecified = value.HasValue;
            }
        }
    }
}
