//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0072_1_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("countryType", Namespace="http://www.ech.ch/xmlns/eCH-0072/1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountryType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1000.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ushort), "1000", "9999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("id", Order=0, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ushort), "0", "999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("unId", Order=1, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort UnIdValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UnId property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UnIdValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ushort> UnId
        {
            get
            {
                if (this.UnIdValueSpecified)
                {
                    return this.UnIdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UnIdValue = value.GetValueOrDefault();
                this.UnIdValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("iso2Id", Order=2, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Iso2Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Z]{3}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{3}")]
        [System.Xml.Serialization.XmlElementAttribute("iso3Id", Order=3, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Iso3Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("shortNameDe", Order=4, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShortNameDe { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("shortNameFr", Order=5, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShortNameFr { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("shortNameIt", Order=6, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShortNameIt { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 60.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(60)]
        [System.Xml.Serialization.XmlElementAttribute("shortNameEn", Order=7, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShortNameEn { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("officialNameDe", Order=8, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OfficialNameDe { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("officialNameFr", Order=9, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OfficialNameFr { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("officialNameIt", Order=10, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OfficialNameIt { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(byte), "0", "9", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("continent", Order=11, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte Continent { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(byte), "0", "9", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("region", Order=12, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte Region { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("state", Order=13, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool State { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RangeAttribute(typeof(ushort), "0", "9999", ConvertValueInInvariantCulture=true)]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("areaState", Order=14, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ushort AreaStateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AreaState property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AreaStateValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 0.</para>
        /// <para xml:lang="en">Maximum inclusive value: 9999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ushort> AreaState
        {
            get
            {
                if (this.AreaStateValueSpecified)
                {
                    return this.AreaStateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AreaStateValue = value.GetValueOrDefault();
                this.AreaStateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("unMember", Order=15, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool UnMember { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1945-01-01.</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("unEntryDate", Order=16, Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime UnEntryDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UnEntryDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UnEntryDateValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1945-01-01.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UnEntryDate
        {
            get
            {
                if (this.UnEntryDateValueSpecified)
                {
                    return this.UnEntryDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UnEntryDateValue = value.GetValueOrDefault();
                this.UnEntryDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("recognizedCh", Order=17, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool RecognizedCh { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1945-01-01.</para>
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("recognizedDate", Order=18, Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime RecognizedDateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RecognizedDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool RecognizedDateValueSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1945-01-01.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> RecognizedDate
        {
            get
            {
                if (this.RecognizedDateValueSpecified)
                {
                    return this.RecognizedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RecognizedDateValue = value.GetValueOrDefault();
                this.RecognizedDateValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("remarkDe", Order=19, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RemarkDe { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("remarkFr", Order=20, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RemarkFr { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("remarkIt", Order=21, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RemarkIt { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("entryValid", Order=22, Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool EntryValid { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum inclusive value: 1945-01-01.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dateOfChange", Order=23, Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime DateOfChange { get; set; }
    }
}
