//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0045_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EventChangeVotingRightsTypeVoterDomainOfInfluenceInfo", Namespace="http://www.ech.ch/xmlns/eCH-0045/4", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EventChangeVotingRightsTypeVoterDomainOfInfluenceInfo
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("domainOfInfluence", Order=0)]
        public Ech0155_4_0.DomainOfInfluenceType DomainOfInfluence { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("countingCircle", Order=1)]
        public Ech0155_4_0.CountingCircleType CountingCircle { get; set; }
    }
}
