//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0045_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("personType", Namespace="http://www.ech.ch/xmlns/eCH-0045/4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("personType", Namespace="http://www.ech.ch/xmlns/eCH-0045/4")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForeignerPersonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwissPersonType))]
    public partial class PersonType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("personIdentification", Order=0)]
        public Ech0044_4_1.PersonIdentificationType PersonIdentification { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Xml.Serialization.XmlElementAttribute("callName", Order=1)]
        public string CallName { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 100.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(100)]
        [System.Xml.Serialization.XmlElementAttribute("allianceName", Order=2)]
        public string AllianceName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("languageOfCorrespondance", Order=3)]
        public LanguageType LanguageOfCorrespondance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("religionData", Order=4)]
        public Ech0011_8_1.ReligionDataType ReligionData { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Order=5)]
        public object Extension { get; set; }
    }
}
