//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0046_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contactType", Namespace="http://www.ech.ch/xmlns/eCH-0046/4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ContactType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("localID", Order=0)]
        public Ech0044_4_1.NamedPersonIdType LocalId { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<AddressType> _address;
        
        [System.Xml.Serialization.XmlElementAttribute("address", Order=1)]
        public System.Collections.Generic.List<AddressType> Address
        {
            get
            {
                return _address;
            }
            set
            {
                _address = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Address collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressSpecified
        {
            get
            {
                return (this.Address != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ContactType" /> class.</para>
        /// </summary>
        public ContactType()
        {
            this._address = new System.Collections.Generic.List<AddressType>();
            this._email = new System.Collections.Generic.List<EmailType>();
            this._phone = new System.Collections.Generic.List<PhoneType>();
            this._internet = new System.Collections.Generic.List<InternetType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<EmailType> _email;
        
        [System.Xml.Serialization.XmlElementAttribute("email", Order=2)]
        public System.Collections.Generic.List<EmailType> Email
        {
            get
            {
                return _email;
            }
            set
            {
                _email = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Email collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmailSpecified
        {
            get
            {
                return (this.Email != null);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<PhoneType> _phone;
        
        [System.Xml.Serialization.XmlElementAttribute("phone", Order=3)]
        public System.Collections.Generic.List<PhoneType> Phone
        {
            get
            {
                return _phone;
            }
            set
            {
                _phone = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Phone collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PhoneSpecified
        {
            get
            {
                return (this.Phone != null);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<InternetType> _internet;
        
        [System.Xml.Serialization.XmlElementAttribute("internet", Order=4)]
        public System.Collections.Generic.List<InternetType> Internet
        {
            get
            {
                return _internet;
            }
            set
            {
                _internet = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Internet collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InternetSpecified
        {
            get
            {
                return (this.Internet != null);
            }
        }
    }
}
