//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0155_5_1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("electronicBallotType", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("electronicBallot", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    public partial class ElectronicBallotType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("electronicBallotIdentification", Order=0)]
        public string ElectronicBallotIdentification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("electronicBallotPosition", Order=1)]
        public string ElectronicBallotPosition { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectronicBallotDescriptionInformationTypeElectronicBallotDescriptionInfo> _electronicBallotDescription;
        
        [System.Xml.Serialization.XmlArrayAttribute("electronicBallotDescription", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("electronicBallotDescriptionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
        public System.Collections.Generic.List<ElectronicBallotDescriptionInformationTypeElectronicBallotDescriptionInfo> ElectronicBallotDescription
        {
            get
            {
                return _electronicBallotDescription;
            }
            set
            {
                _electronicBallotDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ElectronicBallotDescription collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectronicBallotDescriptionSpecified
        {
            get
            {
                return (this.ElectronicBallotDescription != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectronicBallotType" /> class.</para>
        /// </summary>
        public ElectronicBallotType()
        {
            this._electronicBallotDescription = new System.Collections.Generic.List<ElectronicBallotDescriptionInformationTypeElectronicBallotDescriptionInfo>();
            this._electronicBallotGroup = new System.Collections.Generic.List<ElectronicBallotDescriptionInformationTypeElectronicBallotDescriptionInfo>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectronicBallotDescriptionInformationTypeElectronicBallotDescriptionInfo> _electronicBallotGroup;
        
        [System.Xml.Serialization.XmlArrayAttribute("electronicBallotGroup", Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("electronicBallotDescriptionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
        public System.Collections.Generic.List<ElectronicBallotDescriptionInformationTypeElectronicBallotDescriptionInfo> ElectronicBallotGroup
        {
            get
            {
                return _electronicBallotGroup;
            }
            set
            {
                _electronicBallotGroup = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ElectronicBallotGroup collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectronicBallotGroupSpecified
        {
            get
            {
                return (this.ElectronicBallotGroup != null);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("standardElectronicBallot", Order=4)]
        public ElectronicBallotTypeStandardElectronicBallot StandardElectronicBallot { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("variantElectronicBallot", Order=5)]
        public ElectronicBallotTypeVariantElectronicBallot VariantElectronicBallot { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Order=6)]
        public ExtensionType Extension { get; set; }
    }
}
