//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0155_5_1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ElectronicBallotTypeVariantElectronicBallot", Namespace="http://www.ech.ch/xmlns/eCH-0155/5", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ElectronicBallotTypeVariantElectronicBallot
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectronicBallotTypeVariantElectronicBallotQuestionInformation> _questionInformation;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("questionInformation", Order=0)]
        public System.Collections.Generic.List<ElectronicBallotTypeVariantElectronicBallotQuestionInformation> QuestionInformation
        {
            get
            {
                return _questionInformation;
            }
            set
            {
                _questionInformation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ElectronicBallotTypeVariantElectronicBallot" /> class.</para>
        /// </summary>
        public ElectronicBallotTypeVariantElectronicBallot()
        {
            this._questionInformation = new System.Collections.Generic.List<ElectronicBallotTypeVariantElectronicBallotQuestionInformation>();
            this._tieBreakInformation = new System.Collections.Generic.List<ElectronicBallotTypeVariantElectronicBallotTieBreakInformation>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ElectronicBallotTypeVariantElectronicBallotTieBreakInformation> _tieBreakInformation;
        
        [System.Xml.Serialization.XmlElementAttribute("tieBreakInformation", Order=1)]
        public System.Collections.Generic.List<ElectronicBallotTypeVariantElectronicBallotTieBreakInformation> TieBreakInformation
        {
            get
            {
                return _tieBreakInformation;
            }
            set
            {
                _tieBreakInformation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TieBreakInformation collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TieBreakInformationSpecified
        {
            get
            {
                return (this.TieBreakInformation != null);
            }
        }
    }
}
