//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0021_7_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("basedOnLawType", Namespace="http://www.ech.ch/xmlns/eCH-0021/7")]
    public enum BasedOnLawType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("306")]
        Item306,
        
        [System.Xml.Serialization.XmlEnumAttribute("310")]
        Item310,
        
        [System.Xml.Serialization.XmlEnumAttribute("311")]
        Item311,
        
        [System.Xml.Serialization.XmlEnumAttribute("312")]
        Item312,
        
        [System.Xml.Serialization.XmlEnumAttribute("327-a")]
        Item327A,
        
        [System.Xml.Serialization.XmlEnumAttribute("363")]
        Item363,
        
        [System.Xml.Serialization.XmlEnumAttribute("368")]
        Item368,
        
        [System.Xml.Serialization.XmlEnumAttribute("369")]
        Item369,
        
        [System.Xml.Serialization.XmlEnumAttribute("370")]
        Item370,
        
        [System.Xml.Serialization.XmlEnumAttribute("371")]
        Item371,
        
        [System.Xml.Serialization.XmlEnumAttribute("372")]
        Item372,
        
        [System.Xml.Serialization.XmlEnumAttribute("393")]
        Item393,
        
        [System.Xml.Serialization.XmlEnumAttribute("394")]
        Item394,
        
        [System.Xml.Serialization.XmlEnumAttribute("395")]
        Item395,
        
        [System.Xml.Serialization.XmlEnumAttribute("396")]
        Item396,
        
        [System.Xml.Serialization.XmlEnumAttribute("397")]
        Item397,
        
        [System.Xml.Serialization.XmlEnumAttribute("398")]
        Item398,
        
        [System.Xml.Serialization.XmlEnumAttribute("399")]
        Item399,
    }
}
