//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0155_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ballotQuestionType", Namespace="http://www.ech.ch/xmlns/eCH-0155/4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BallotQuestionType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<BallotQuestionTypeBallotQuestionInfo> _ballotQuestionInfo;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ballotQuestionInfo", Order=0)]
        public System.Collections.Generic.List<BallotQuestionTypeBallotQuestionInfo> BallotQuestionInfo
        {
            get
            {
                return _ballotQuestionInfo;
            }
            set
            {
                _ballotQuestionInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BallotQuestionType" /> class.</para>
        /// </summary>
        public BallotQuestionType()
        {
            this._ballotQuestionInfo = new System.Collections.Generic.List<BallotQuestionTypeBallotQuestionInfo>();
        }
    }
}
