//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0155_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tieBreakQuestionType", Namespace="http://www.ech.ch/xmlns/eCH-0155/4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TieBreakQuestionType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<TieBreakQuestionTypeTieBreakQuestionInfo> _tieBreakQuestionInfo;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tieBreakQuestionInfo", Order=0)]
        public System.Collections.Generic.List<TieBreakQuestionTypeTieBreakQuestionInfo> TieBreakQuestionInfo
        {
            get
            {
                return _tieBreakQuestionInfo;
            }
            set
            {
                _tieBreakQuestionInfo = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TieBreakQuestionType" /> class.</para>
        /// </summary>
        public TieBreakQuestionType()
        {
            this._tieBreakQuestionInfo = new System.Collections.Generic.List<TieBreakQuestionTypeTieBreakQuestionInfo>();
        }
    }
}
