//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0097_4_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("uidOrganisationIdCategorieType", Namespace="http://www.ech.ch/xmlns/eCH-0097/4")]
    [System.Xml.Serialization.XmlRootAttribute("uidOrganisationIdCategorieType", Namespace="http://www.ech.ch/xmlns/eCH-0097/4")]
    public enum UidOrganisationIdCategorieType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("CHE")]
        Che,
        
        [System.Xml.Serialization.XmlEnumAttribute("ADM")]
        Adm,
    }
}
