//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0157_5_1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EventInitialDeliveryElectionGroupElectionInformation", Namespace="http://www.ech.ch/xmlns/eCH-0157/5", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EventInitialDeliveryElectionGroupElectionInformation
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("election", Order=0)]
        public Ech0155_5_1.ElectionType Election { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Ech0155_5_1.CandidateType> _candidate;
        
        [System.Xml.Serialization.XmlElementAttribute("candidate", Order=1)]
        public System.Collections.Generic.List<Ech0155_5_1.CandidateType> Candidate
        {
            get
            {
                return _candidate;
            }
            set
            {
                _candidate = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Candidate collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CandidateSpecified
        {
            get
            {
                return (this.Candidate != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EventInitialDeliveryElectionGroupElectionInformation" /> class.</para>
        /// </summary>
        public EventInitialDeliveryElectionGroupElectionInformation()
        {
            this._candidate = new System.Collections.Generic.List<Ech0155_5_1.CandidateType>();
            this._list = new System.Collections.Generic.List<Ech0155_5_1.ListType>();
            this._listUnion = new System.Collections.Generic.List<Ech0155_5_1.ListUnionType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Ech0155_5_1.ListType> _list;
        
        [System.Xml.Serialization.XmlElementAttribute("list", Order=2)]
        public System.Collections.Generic.List<Ech0155_5_1.ListType> List
        {
            get
            {
                return _list;
            }
            set
            {
                _list = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the List collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListSpecified
        {
            get
            {
                return (this.List != null);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<Ech0155_5_1.ListUnionType> _listUnion;
        
        [System.Xml.Serialization.XmlElementAttribute("listUnion", Order=3)]
        public System.Collections.Generic.List<Ech0155_5_1.ListUnionType> ListUnion
        {
            get
            {
                return _listUnion;
            }
            set
            {
                _listUnion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListUnion collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListUnionSpecified
        {
            get
            {
                return (this.ListUnion != null);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("extension", Order=4)]
        public Ech0155_5_1.ExtensionType Extension { get; set; }
    }
}
