//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.963.0
namespace Ech0155_5_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.963.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("domainOfInfluenceTypeType", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    public enum DomainOfInfluenceTypeType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("CH")]
        Ch,
        
        [System.Xml.Serialization.XmlEnumAttribute("CT")]
        Ct,
        
        [System.Xml.Serialization.XmlEnumAttribute("BZ")]
        Bz,
        
        [System.Xml.Serialization.XmlEnumAttribute("MU")]
        Mu,
        
        [System.Xml.Serialization.XmlEnumAttribute("SC")]
        Sc,
        
        [System.Xml.Serialization.XmlEnumAttribute("KI")]
        Ki,
        
        [System.Xml.Serialization.XmlEnumAttribute("OG")]
        Og,
        
        [System.Xml.Serialization.XmlEnumAttribute("KO")]
        Ko,
        
        [System.Xml.Serialization.XmlEnumAttribute("SK")]
        Sk,
        
        [System.Xml.Serialization.XmlEnumAttribute("AN")]
        An,
    }
}
