//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0155_5_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("voteType", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("vote", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
    public partial class VoteType
    {
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("voteIdentification", Order=0)]
        public string VoteIdentification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("domainOfInfluence", Order=1)]
        public DomainOfInfluenceType DomainOfInfluence { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<VoteDescriptionInformationTypeVoteDescriptionInfo> _voteDescription;
        
        [System.Xml.Serialization.XmlArrayAttribute("voteDescription", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("voteDescriptionInfo", Namespace="http://www.ech.ch/xmlns/eCH-0155/5")]
        public System.Collections.Generic.List<VoteDescriptionInformationTypeVoteDescriptionInfo> VoteDescription
        {
            get
            {
                return _voteDescription;
            }
            set
            {
                _voteDescription = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the VoteDescription collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VoteDescriptionSpecified
        {
            get
            {
                return (this.VoteDescription != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="VoteType" /> class.</para>
        /// </summary>
        public VoteType()
        {
            this._voteDescription = new System.Collections.Generic.List<VoteDescriptionInformationTypeVoteDescriptionInfo>();
        }
    }
}
