//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0021_8_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("birthAddonDataType", Namespace="http://www.ech.ch/xmlns/eCH-0021/8")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BirthAddonDataType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<NameOfParentType> _nameOfParent;
        
        [System.Xml.Serialization.XmlElementAttribute("nameOfParent", Order=0)]
        public System.Collections.Generic.List<NameOfParentType> NameOfParent
        {
            get
            {
                return _nameOfParent;
            }
            set
            {
                _nameOfParent = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the NameOfParent collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NameOfParentSpecified
        {
            get
            {
                return (this.NameOfParent != null);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BirthAddonDataType" /> class.</para>
        /// </summary>
        public BirthAddonDataType()
        {
            this._nameOfParent = new System.Collections.Generic.List<NameOfParentType>();
        }
    }
}
