//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0021_8_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("civilDefenseDataType", Namespace="http://www.ech.ch/xmlns/eCH-0021/8")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CivilDefenseDataType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("civilDefense", Order=0)]
        public Ech0011_9_0.YesNoType CivilDefenseValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CivilDefense property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CivilDefenseValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Ech0011_9_0.YesNoType> CivilDefense
        {
            get
            {
                if (this.CivilDefenseValueSpecified)
                {
                    return this.CivilDefenseValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CivilDefenseValue = value.GetValueOrDefault();
                this.CivilDefenseValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("civilDefenseValidFrom", Order=1, DataType="date")]
        public System.DateTime CivilDefenseValidFromValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CivilDefenseValidFrom property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CivilDefenseValidFromValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> CivilDefenseValidFrom
        {
            get
            {
                if (this.CivilDefenseValidFromValueSpecified)
                {
                    return this.CivilDefenseValidFromValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CivilDefenseValidFromValue = value.GetValueOrDefault();
                this.CivilDefenseValidFromValueSpecified = value.HasValue;
            }
        }
    }
}
