//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0021_8_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GuardianRelationshipTypePartner", Namespace="http://www.ech.ch/xmlns/eCH-0021/8", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardianRelationshipTypePartner
    {
        
        [System.Xml.Serialization.XmlElementAttribute("personIdentification", Order=0)]
        public Ech0044_4_1.PersonIdentificationType PersonIdentification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("personIdentificationPartner", Order=1)]
        public Ech0044_4_1.PersonIdentificationLightType PersonIdentificationPartner { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("partnerIdOrganisation", Order=2)]
        public Ech0011_9_0.PartnerIdOrganisationType PartnerIdOrganisation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Order=3)]
        public Ech0010_8_0.MailAddressType Address { get; set; }
    }
}
