//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator
namespace Ech0021_8_0
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("lockDataType", Namespace="http://www.ech.ch/xmlns/eCH-0021/8")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LockDataType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("addressLock", Order=0)]
        public AddressLockType AddressLock { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("addressLockValidFrom", Order=1, DataType="date")]
        public System.DateTime AddressLockValidFromValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AddressLockValidFrom property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AddressLockValidFromValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> AddressLockValidFrom
        {
            get
            {
                if (this.AddressLockValidFromValueSpecified)
                {
                    return this.AddressLockValidFromValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AddressLockValidFromValue = value.GetValueOrDefault();
                this.AddressLockValidFromValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("addressLockValidTill", Order=2, DataType="date")]
        public System.DateTime AddressLockValidTillValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the AddressLockValidTill property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AddressLockValidTillValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> AddressLockValidTill
        {
            get
            {
                if (this.AddressLockValidTillValueSpecified)
                {
                    return this.AddressLockValidTillValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AddressLockValidTillValue = value.GetValueOrDefault();
                this.AddressLockValidTillValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dataLock", Order=3)]
        public DataLockType DataLock { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("dataLockValidFrom", Order=4, DataType="date")]
        public System.DateTime DataLockValidFromValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DataLockValidFrom property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DataLockValidFromValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> DataLockValidFrom
        {
            get
            {
                if (this.DataLockValidFromValueSpecified)
                {
                    return this.DataLockValidFromValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DataLockValidFromValue = value.GetValueOrDefault();
                this.DataLockValidFromValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("dataLockValidTill", Order=5, DataType="date")]
        public System.DateTime DataLockValidTillValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DataLockValidTill property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DataLockValidTillValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> DataLockValidTill
        {
            get
            {
                if (this.DataLockValidTillValueSpecified)
                {
                    return this.DataLockValidTillValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DataLockValidTillValue = value.GetValueOrDefault();
                this.DataLockValidTillValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("paperLock", Order=6)]
        public PaperLockType PaperLock { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("paperLockValidFrom", Order=7, DataType="date")]
        public System.DateTime PaperLockValidFromValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PaperLockValidFrom property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PaperLockValidFromValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> PaperLockValidFrom
        {
            get
            {
                if (this.PaperLockValidFromValueSpecified)
                {
                    return this.PaperLockValidFromValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PaperLockValidFromValue = value.GetValueOrDefault();
                this.PaperLockValidFromValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("paperLockValidTill", Order=8, DataType="date")]
        public System.DateTime PaperLockValidTillValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PaperLockValidTill property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PaperLockValidTillValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> PaperLockValidTill
        {
            get
            {
                if (this.PaperLockValidTillValueSpecified)
                {
                    return this.PaperLockValidTillValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PaperLockValidTillValue = value.GetValueOrDefault();
                this.PaperLockValidTillValueSpecified = value.HasValue;
            }
        }
    }
}
